from . import company_management_settings
from . import company_management_role
from . import res_users
from . import company_management_transaction_reference
from . import company_management_tax_item
from . import company_management_tax_group
from . import company_management_goods_tax_type
from . import company_management_fiscal_year
from . import company_management_payment_term
from . import company_management_shipping_company
